name: CI-build_and_deploy-site

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/ntlg-dplm
  TAG: ${{ github.run_number }}

on:
  push:
    branches:
    - main
    tags:
    - '*'
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Get files
      uses: actions/checkout@v3
    
    - name: Echo tag
      run: echo "${GITHUB_REF:10}" >> $GITHUB_ENV
      
    - name: Set env TAG
      run: echo "TAG=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/tags/v')
      
    - name: Echo env TAG
      run: echo "${TAG}"
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.TAG }}
    
    - name: Push the Docker image
      run: |
        docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ env.IMAGE_NAME }}:${{ env.TAG }}
